### ISSUE TITLE
OR query for users resolver

### ISSUE THREAD

**Issue by Fi1osof** [ian13456/mc.js#10]
**Is your feature request related to a problem? Please describe.**
[Here](https://github.com/ian13456/mc.js/blob/656d6f63399c2897f2b99eefa96cc1fbd284039e/server/src/resolvers/queries/userQueries.js#L21-L27) uses where owerride if query argument passed. 

**Describe the solution you'd like**
[Here](https://github.com/prisma-cms/server/blob/master/src/server/index.mjs#L34) me solution for merge queries.
With this we can use both args (query and other (including OR)).

More info: https://prisma-cms.com/topics/kastomnye-usloviya-poiska-v-@prisma-cms.html (sorry, in russian).

Here example of use: https://github.com/prisma-cms/prisma-cms.com/blob/0fe462748a5d40ad7834b1c8dde242a3d2b01bfc/src/server/modules/user/index.mjs#L805-L877

**Comment by ian13456** [comment]
Could you clarify on the feature you're trying to request? Also, The `users` query is currently not used anywhere in the project, but it would be nice to have additional and potentially useful functionality on other queries.

**Comment by Fi1osof** [comment]
prisma generates CRUD schema on each types. For type User it's **user, users, usersConnection, delete, deleteMany** and Subscription **user**.
Native queries **users** and **usersConnection** uses input argument **UserWhereInput**. 
In your custom schema you [override](https://github.com/ian13456/mc.js/blob/656d6f63399c2897f2b99eefa96cc1fbd284039e/server/src/schema.graphql#L2) query **user** and remove args **orderBy** and **where** and added arg **query**. By using [merge-graphql-schemas](https://github.com/Urigo/merge-graphql-schemas) you may extend input UserWhereInput.
```
input UserWhereInput{
   query: String
}
```
and got complete UserWhereInput with other native **where** params and your **query**. And we can query
```

query users (
  where: {
    worlds_some: {
      type: DEFAULT
    }
    query: "name"
  }
){
   id
   worlds{
       id
   }
}
```

My solution helps to inject such queries.

**Comment by ian13456** [comment]
I get what you mean now, but the `users` query isn't used in the project so far. However, I see a great potential usage for [merge-graphql-schemas] on the `myWorlds` query for pagination. I will implement that into the project in the future. Or maybe you could create a pull request for this? That'd be awesome!

**Comment by Fi1osof** [comment]
Send PR #13 
Does not containt where injection yet, but will after checkout and approve.
