### ISSUE TITLE
See other users in multiplay

### ISSUE THREAD

**Issue by Fi1osof** [ian13456/mc.js#11]
**Is your feature request related to a problem? Please describe.**
See title

**Comment by ian13456** [comment]
Hi, there's another branch called `feat/multiplayer` but I haven't rebased it for a while. It's still missing a lot of key multiplayer features and optimizations waiting to be implemented though.
![Screenshot from 2019-08-11 19-55-44](https://user-images.githubusercontent.com/35216312/62833492-4ddaf680-bc72-11e9-8cbb-9c14f55e2b56.png)

**Comment by Fi1osof** [comment]
Thanks! Will wait for this.

**Comment by ian13456** [comment]
I just pushed a rebased version. Check it out!

**Comment by Fi1osof** [comment]
You rock!
Now realy cool!
Thanks!
