### ISSUE TITLE
Add proxy rewrite 

### ISSUE THREAD

**Issue by Fi1osof** [ian13456/mc.js#17]
**Is your feature request related to a problem? Please describe.**
React-scripts allow configure proxy rewriting: https://facebook.github.io/create-react-app/docs/proxying-api-requests-in-development#configuring-the-proxy-manually

**Describe the solution you'd like**
add src/setupProxy.js
```
var proxy = require('http-proxy-middleware');

module.exports = function (app) {

  app.use(proxy('/ws.js/socket.io/', {
    pathRewrite: { '^/ws.js': '' },
    target: 'http://localhost:5000',
    ws: true,
  }));

};
```

P.S. [core/config/config.js](https://github.com/ian13456/mc.js/blob/aaa47fdb789b41ae9826d7e2e97ed6b9b7ee62bf/core/lib/ioClient/ioClient.js#L8) not allow set my relation path for ws connections. I had to set like this:
```
const socket = socketIOClient({
    path: '/ws.js/socket.io/',
  })
```

**Comment by ian13456** [comment]
Hi, what is ws.js in this context?

**Comment by Fi1osof** [comment]
It's just a custom relative path.
https://socket.io/docs/server-api/

Option | Default value | Description
-- | -- | --
path | /socket.io | name of the path to capture

**Comment by ian13456** [comment]
So should localhost:4000 be included as a proxy as well?

**Comment by Fi1osof** [comment]
I will rewrite [this](https://github.com/ian13456/mc.js/blob/master/server/src/lib/server/socketIO.js) in a few days and remove socket.io from server. Will be use native prisma sockets.

**Comment by ian13456** [comment]
Ok! Sounds good!
