### ISSUE TITLE
Delete world issue

### ISSUE THREAD

**Issue by ian13456** [ian13456/mc.js#21]
**Describe the bug**
Error on deleting a world.

**To Reproduce**
1. Create a world
2. Close world and go to worlds list
3. Click on a world and delete

**Expected behavior**
Navigate to `DeleteWorld`

**Screenshots**
![image](https://user-images.githubusercontent.com/35216312/62926152-7b48b100-bde6-11e9-9912-f92d946f8374.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Opera

**Additional context**
@Fi1osof I think it has to do with `merge-graphql-schema` since I did some testing and `deleteWorld` mutation doesn't seem to work. Can you take a look at it?

**Comment by ian13456** [comment]
By the way, @Fi1osof it would be nice if you could get the eslint plugin on vs-code since it highlights the lines that violates the eslint rules of the project. :+1:

**Comment by Fi1osof** [comment]
@ian13456 this is not only my error. [Here](https://github.com/ian13456/mc.js/blob/4cc0d0218fe913b468c572b95db20395515fc627/src/components/Game/Worlds/Buttons/DeleteWorld/DeleteWorld.js#L20) world data not exists yet (still loading).
I'll fix now.

> By the way, @Fi1osof it would be nice if you could get the eslint plugin on vs-code since it highlights the lines that violates the eslint rules of the project. +1

Which one? Give me link, please.

**Comment by ian13456** [comment]
Thanks for your time! [Here](https://github.com/microsoft/vscode-eslint)’s the link to elaine. Eslint keeps the coding style of a project consistent. I’ll take a look at your pull request in a bit👍

**Comment by Fi1osof** [comment]
Thanks! Got it.

**Comment by ian13456** [comment]
I just merged the pull request! Nice work :smile:
