### ISSUE TITLE
Projects Board

### ISSUE THREAD

**Issue by kloppz** [ian13456/mc.js#28]
Hi! suggestion,
you can active Projects from github and create tasks features or others to the collaboratos can pick 1 and help you in development :)

**Comment by ian13456** [comment]
Sounds like a great idea! So if i create a project with TODO lists on it can other people see it?

**Comment by kloppz** [comment]
Yes! its visible to all, and u can select who can move tasks etc, and when we have PR, we can "tag" issue

**Comment by ian13456** [comment]
Does sound appealing :thinking: I'll create one now.

**Comment by kloppz** [comment]
https://help.github.com/en/articles/about-project-boards u see info here

**Comment by kloppz** [comment]
nice,  suggestions:
- create column review to PR
- create all features TODO https://github.com/ian13456/mc.js/blob/master/TODO.md in project
- set auto create task in project when PR or when issue and auto close if u merge PR

**Comment by kloppz** [comment]
you need configure to autoset project when PR
