### ISSUE TITLE
Microsoft owns Minecraft, how is this not a copyright violation

### ISSUE THREAD

**Issue by 00benallen** [ian13456/mc.js#5]
See title

**Comment by ian13456** [comment]
I think it is. I’m going to change the name today after I come up with one. Got any suggestions?

**Comment by jafin** [comment]
CraftYourMineJs
MineyMcCraftFace

**Comment by ian13456** [comment]
I just changed the project name.

**Comment by ShayBox** [comment]
on this topic, you should remove any assets from the game, including buttons and backgrounds

**Comment by Fi1osof** [comment]
> on this topic, you should remove any assets from the game, including buttons and backgrounds

F*ck MS, open source forever!

**Comment by ian13456** [comment]
@ShayBox What if I create my own textures or background?

**Comment by ShayBox** [comment]
I mean remove the minecraft textures that are in the project, creating your own is fine, although there is a grey area to how close I would make them

**Comment by Fi1osof** [comment]
> Although I agree, open source forever, Microsoft didn't make Minecraft closed source, they didn't even make Minecraft, if you want to hate Microsoft pick an actual reason to hate them.

I do not hate MS. I hate code closure and all kinds of patents.
