### ISSUE TITLE
Play without installing on PC. Main website for repository.

### ISSUE THREAD

**Issue by lomeat** [ian13456/mc.js#52]
**Is your feature request related to a problem? Please describe.**
No. Yes. I want to play withought installation.

**Describe the solution you'd like**
Deploy anywhere, like an Amazon.

**Describe alternatives you've considered**
Make Lite version only with Front-end (game playground) and simple deploy to GH Pages, Netlify

**Comment by ian13456** [comment]
I might make a version wich only runs client side and stores data in indexedDB or localStorage in the future, shouldn't be too hard🤷‍♂
