### ISSUE TITLE
Idea: Use Electron To Remove Need of Browsing to Localhost

### ISSUE THREAD

**Issue by zodywoolsey** [ian13456/mc.js#53]
**Is your feature request related to a problem? Please describe.**
No. Current users have a confusing set of instructions to get started. Adoption could grow if we streamline some of the process.

**Describe the solution you'd like**
If we migrate to Electron we could see performance improvements and will see an easier startup.

**Describe alternatives you've considered**
Use Electron, if it's a reasonable change.

**Comment by zodywoolsey** [comment]
I just realized another thing about the current setup. I am unable to install docker on my personal machine and thus cannot help with or run the project.

**Comment by ian13456** [comment]
#39 
> But wouldn’t that defeat the purpose of this project (minecraft in the browser)? If we create a stand-alone app with electron then it’s basically [minetest](https://github.com/minetest/minetest) right?

I've been thinking about it recently actually because some people can't seen to download Docker either :/

I've also thought of making a separate version which uses localStorage or indexedDB as data storage, but I haven't tried it yet. Should I turn this into a standalone app?

**Comment by sr229** [comment]
I'm against using Electron. Not only you're supplying a modified Chromium that has so much deviation from vanilla browser parity, you're supplying a browser that eats more than 100MB. I  suggest either porting this for Proton Native (React Native for Desktops) or equivalent instead.

**Comment by ian13456** [comment]
Good point. Well I'm not an expert at any of these so I don't really have a standpoint on this one :/

**Comment by zodywoolsey** [comment]
I just think the application should be more distributable. I guess I'm not understanding why node.js isn't sufficient on its own.

**Comment by ian13456** [comment]
Should I make a discord server or what not to discuss issues as such? :thinking:

**Comment by kloppz** [comment]
Hi! Slack better! Create a slack to project

**Comment by zodywoolsey** [comment]
That might be a good idea. I think an outline of the intended use case might be a good idea.
I think I get it now. This project is designed to be hosted on a server and presented as a web portal to the game, right? If so, I misunderstood and thought it was just a clone with the sole intention being to have it run on JS.

**Comment by zodywoolsey** [comment]
Slack would be good.
Discord might be better in this case, if there is any intention to have a community form around the project.

**Comment by ian13456** [comment]
@zodywoolsey I think you didn't misunderstand XD it is a clone of Minecraft. Unless there's any future plans on the actual game integration, the project remains to be a JS edition of Minecraft.

So should I create a discord server or a slack server?

**Comment by zodywoolsey** [comment]
@ian13456 I would still say a Discord would be better. It's already widespread in the gaming community and is much more community-oriented. Slack would be better if there were a specific team of devs that don't really need to dynamically expand very much, or need more professional level tools for collaboration among themselves.

Ok, I was just wanting to make sure I wasn't missing some second part of the project lol. I think if the primary focus is to make a Minecraft clone on js it would benefit from easy setup and easy running after install (for devs or those who would rather have a client) . If we used electron we wouldn't need to rely on it specifically, it would just be a good way to speed up the setup/testing/running part right now.

**Comment by sr229** [comment]
I suggest using Slack. Yarnpkg uses Discord due to the large amount of people in its community, and it'll allow us to have the same fine-grained permissions as Slack does, add the fact we have a large bot marketplace.

Discord also promotes Open Source so we can get partnered status by being a Open Source project*

> * there's a specific star requirement for this.

**Comment by ian13456** [comment]
I just created a discord. It's the `chat` badge on README.md.
