### ISSUE TITLE
Suggestion: Switch over to TypeScript

### ISSUE THREAD

**Issue by JasonHK** [ian13456/mc.js#55]
Will you considered rewrite the project using TypeScript? I think it can improve the maintainability of the project.

**Comment by kappaxbeta** [comment]
Please don't do it. TypeScript was great in the year it came out, but now it's outdated. The Main reason was that JavaScript has no OOP. But now-days, its no problem just use Babel and maybe if you need typesage, just use flow. Also TypeScript lacking updates, when new React updates coming, so you need to wait. In my humble opinion TypeScript kills the JS magic ☮️

**Comment by ian13456** [comment]
Typescript is good for projects that emphasizes on the importance of types...right? I personally don't really think that's too big of an issue for the project although I would agree that Typescript could potentially improve the maintainability of the project. I won't change the project for now but would definitely would appreciate if anyone's brave enough to take on that task :thinking:
