### ISSUE TITLE
Consider using WebAssembly for Performance Reasons

### ISSUE THREAD

**Issue by sr229** [ian13456/mc.js#58]
WebAssembly is a new language for the web that allows native languages to leverage the Web as its target. It's should also theoretically more optimized and allows us to use something other than JS to code the game via Emscripten.

There's a lot of WebAssembly ports of popular games, most notably id Tech 4 being ported to WebAssembly and still hit framerates as native as a natively-compiled counterpart.

**Comment by ian13456** [comment]
Good idea! Do you have any suggestions as to where WebAssembly can be used in this project?

**Comment by sr229** [comment]
@ian13456 I believe *everything*. Terrain generation is something JavaScript may screw up due to its quirky Number system, Player positioning is something that requires precise calculations, JavaScript should never be used on those, amongst other things.

**Comment by ian13456** [comment]
I'll try my best!
