### ISSUE TITLE
Project precursor: voxel.js

### ISSUE THREAD

**Issue by cboulanger** [ian13456/mc.js#6]
Since you don't mention it (specifically): do you know about Max Ogden's & Substack's Project voxel.js from 2013? 

https://maxogden.com/bringing-minecraft-style-games-to-the-open-web.html
https://eventil.com/talks/6XSN1p-max-ogden-minecraft-js/transcript

**Comment by ian13456** [comment]
Yup, I really like the project but sadly there hasn't been much activity going on on the libraries, so most of the voxel.js modules are outdated (uses outdated three.js). 

Nevertheless I still use the modules as a reference whenever I encouter any problems, such as the sky in mc.js is actually adapted from [voxel-sky](https://github.com/shama/voxel-sky).

Another great project similar to voxel-js is the [noa engine](https://github.com/andyhall/noa), in fact the [minecraft website version](classic.minecraft.net) uses it!

**Comment by cboulanger** [comment]
Yes, the project was not continued. But maybe it would be interesting to add a small history section to the readme... Good luck with your project!

**Comment by ian13456** [comment]
Thanks! Sounds like a good idea to me. I'll add it sometime in the near future!
