### ISSUE TITLE
yarn deploy error

### ISSUE THREAD

**Issue by Fi1osof** [ian13456/mc.js#9]
**Describe the bug**
error Command "graphql" not found.

**To Reproduce**
yarn run deploy

Solution: 
yarn add graphql-cli

Probably you have installed globaly.

**Comment by ian13456** [comment]
I wrote this in the readme:

> Before cloning the repo or doing anything, be sure to install docker, node, prisma-cli and graphql-cli on your computer.

The `graphql` command belongs to `graphql-cli`, but I probably should state it more clearly. I'll make a change soon.
